### ISSUE TITLE
Dev instructions

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#1]
@webilhan, would you mind adding a quick dev guide on the main readme, pls? Just something like `npm i`, `node run dev` or whatever it takes to confirm we're not pushing bad content.

**Comment by onthebreeze** [comment]
does this duplicate #7 ?

**Comment by webilhan** [comment]
@nissimsan Added short instructions.

**Comment by nissimsan** [comment]
Looks good, @webilhan - cheers!
