### ISSUE TITLE
Implement editorial process

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#11]
Appreciating the "first cut" approach done here already. But for this to be an actual standard, and not a dictatorship or the wild west, we need procedures on minimum editor approvals, merge ordering, and such practicalities. 

For example, https://github.com/uncefact/spec-untp/pull/4 now has an unfair merge conflict because... someone... (Cough, cough, ... cough-Steve...)  made direct updates to `main`. 

IMO the time is now to get this in place. 

Volunteering as editor. 

Also happy to PR a concrete suggestion on the github procedures. But happy if someone else beats me to it... (via a PR)

**Comment by nissimsan** [comment]
I added branch protection on main. Two approvals. Let's try that out, we can always modify...

**Comment by nissimsan** [comment]
(Copied over from the meeting chat) 
Jo Spencer
What we're talking about is a supply chain point governance graph that defines what's required at that point. The rules need to define the list of credentials, issued by a number of issuers and attribute specifics required to successfully process / progress the supply chain activity

**Comment by onthebreeze** [comment]
Agreed.  Editorial process is now in place and this issue can be closed.
