### ISSUE TITLE
Should the UNTP allow third parties redefining spec related vocabulary

### ISSUE THREAD

**Issue by PatStLouis** [uncefact/spec-untp#116]
Should we protect terms defined by this specification? The UNTP defines some terms such as `ConformityAttestation`. Do we want to allow third parties redefining what a `ConformityAttestation` (or any other vocabulary defined in this specification) means in their UNTP credentials with an arbitrary definition?

@nissimsan @zachzeus @onthebreeze @ashleythedeveloper

**Comment by Fak3** [comment]
We should protect core classes like `ConformityAttestation` at the root context. But only protect properties in the type-scoped or property-scoped subcontexts, to allow downstream extensions developers freedom to redefine generic properties like `scope` within the subcontext of their own custom defined classes.

**Comment by PatStLouis** [comment]
It seems we have agreement that UNTP defined types and scoped properties should be defined. I will close this issue if no further comments are made.

**Comment by onthebreeze** [comment]
Agreed - all UNTP terms now protected
