### ISSUE TITLE
Product.modelName is missing from diagram and context

### ISSUE THREAD

**Issue by Fak3** [uncefact/spec-untp#129]
Sample DPP includes `"modelName": "Cruizer",` but this field is missing from the diagram and json-ld context file

**Comment by onthebreeze** [comment]
yes because the sample was created separately to the model.  Hopefully fixed now and into the future

**Comment by onthebreeze** [comment]
Thank you, that was a bug.  modelName is now just "name" and all artifacts fixed https://test.uncefact.org/vocabulary/untp/dpp/0/about
