### ISSUE TITLE
Units of Measure

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#132]
Product dimensions and other units of measure should make use of UN/ECE Recommendation 20. See http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_rev3_Annex3e.pdf.

This is used by schema.org and GS1 Web Voc. See, for example, https://ref.gs1.org/voc/unitCode. 

In practice, awkward and counter-intuitive as it may be, uppercase GRM is used rather than the more natural 'g', etc.

**Comment by onthebreeze** [comment]
we require Rec20 Units
