### ISSUE TITLE
Performance scorecards

### ISSUE THREAD

**Issue by ReLOG3PSNE** [uncefact/spec-untp#138]
@onthebreeze & All, ref. the Performance scorecards subject as mentioned in the last meetings, I also deem possibly useful to consider the **Ecodesign for Sustainable Products Regulation** (**ESPR**) (ref. [here ](https://commission.europa.eu/energy-climate-change-environment/standards-tools-and-labels/products-labelling-rules-and-requirements/sustainable-products/ecodesign-sustainable-products-regulation_en)and [here](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32024R1781&qid=1719580391746)), which entered into force on 18 July 2024, and is part of the approach to more environmentally sustainable and circular products.

The ESPR is part of [a package of measures](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A52022DC0140&qid=1649112555090) that are central to achieving the objectives of the [2020 Circular Economy Action Plan](https://environment.ec.europa.eu/strategy/circular-economy-action-plan_en) and enables the setting of performance and information conditions – known as ‘ecodesign requirements’ – for almost all categories of physical goods (with some exceptions, such as food and feed, as defined in [Regulation 178/2002](https://eur-lex.europa.eu/eli/reg/2002/178/oj)), including to:-

- Improve product durability, reusability, upgradability and reparability
- Make products more energy and resource-efficient
- Address the presence of substances that inhibit circularity
- Increase recycled content
- Make products easier to remanufacture and recycle
- Set rules on carbon and environmental footprints
- Improve the availability of information on product sustainability

Last, surely not least, also contains/relates to a number of other measures:

**- Digital Product Passport**
- Rules to address destruction of unsold consumer products
- Green Public Procurement

Thought worth sharing

**Comment by onthebreeze** [comment]
It’s an impressively large piece of regulation But, as yet, I’m not aware of any commodity specific delegated acts the specify the detailed data requirements or performance calculation rule requirements So until then we can only make our best guess?Steven CapellMob: 0410 437854On 1 Aug 2024, at 5:26 PM, Stefano Negrini - ReLOG3P ***@***.***> wrote:﻿
@onthebreeze & All, ref. the Performance scorecards subject as mentioned in the last meetings, I also deem possibly useful to consider the Ecodesign for Sustainable Products Regulation (ESPR) (ref. here and here), which entered into force on 18 July 2024, and is part of the approach to more environmentally sustainable and circular products.
The ESPR is part of a package of measures that are central to achieving the objectives of the 2020 Circular Economy Action Plan and enables the setting of performance and information conditions – known as ‘ecodesign requirements’ – for almost all categories of physical goods (with some exceptions, such as food and feed, as defined in Regulation 178/2002), including to:-

Improve product durability, reusability, upgradability and reparability
Make products more energy and resource-efficient
Address the presence of substances that inhibit circularity
Increase recycled content
Make products easier to remanufacture and recycle
Set rules on carbon and environmental footprints
Improve the availability of information on product sustainability

Last, surely not least, also contains/relates to a number of other measures:
- Digital Product Passport

Rules to address destruction of unsold consumer products
Green Public Procurement

Thought worth sharing
