### ISSUE TITLE
Require batch if serialized?

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#143]
I note that https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport#product requires that if a serial number of provided, a batch number MUST also be provided. What's the justification for this? I have a feeling this might not be possible in all cases and suggest that it be at most SHOULD, if not MAY.

**Comment by onthebreeze** [comment]
OK fair enough - agreed.

**Comment by onthebreeze** [comment]
The text is poorly written.  It says

"DPPs may be issued at product class level (i.e. all shoes of the same model) or at the individual item level (ie this specific serialised pair of shoes). serialNumber and/or batchNumber MUST be provided if the DPP is issued at item level."

What it is trying to say is that IF your DPP is about a specific product instance (not a class) then a batch OR serial number must be present.  It is perhaps stating the obvious in a confusing way.  What if we split that bullet point into three like this:

* DPPs issued at class level (eg all instances of the same model of shoe) MUST NOT include item serial numbers and MAY include a batch number.
* DPPs issued at item level (eg a specific shoe) MUST include the item serial number and MAY include a batch number
* DPPs for bulk commodities (eg bales of cotton) SHOULD include a batch number. 

or something like that?

**Comment by philarcher** [comment]
Thanks! Closing.
