### ISSUE TITLE
contexts should be versioned

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#149]
This is a bug, given the context versioning which was just discussed on the call. Should be pointing at a versioned context: 
https://github.com/uncefact/spec-untp/pull/148/files#diff-4bbcb3ee3ac7bb4b1daebee238598ef0574447b6bdb59a82c90bbd54d509604d

**Comment by nissimsan** [comment]
Continuing this topic, as I just raised on the call, very frequently updated contexts is an anti-pattern. 

A strategy for versioning of contexts - but also the other related files especially schema - is needed.

**Comment by onthebreeze** [comment]
All context files are now versioned - for example DPP context version history is here https://test.uncefact.org/vocabulary/untp/dpp/0/versions
