### ISSUE TITLE
Implementation registration for software [VERA]

### ISSUE THREAD

**Issue by RickySpherity** [uncefact/spec-untp#157]
# General Information 

### Organisation data

Organisation name : Spherity
Organisation homepage URL : https://www.spherity.com/
Logo (please attach approx 300x300px png logo to this issue)
Registration country : Germany
Operating countries : global
Industry sectors :582

### Implementation statement

Spherity is a global leader in digital identity solutions, focused on improving secure identity management for enterprises, products, and supply chains. Our self-sovereign identity (SSI) technology ensures compliance with data protection regulations and streamlines operations. We offer CARO for authentication and authorization in the US pharmaceutical supply chain, and VERA for the Digital Product Passport across multiple industries. Supporting UNTP implementation aligns with our mission to enhance transparency, accountability, and trust, benefiting our stakeholders and the industries we serve.

### Implementation Status

- [ X ] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ X ] Digital Product Passport
- [ X ] Digital Facility Record
- [ X ] Digital Traceability Event
- [ X ] Digital Conformity Credential
- [ X ] Digital Identity Resolver
- [ X ] Decentralised Access Control
- [ X ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [ ] Pre-release pilot versions 0.x.x
- [ X ] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Please list any industry associations of which you are a member and which may be a focal point for a UNTP [community activation program](https://uncefact.github.io/spec-untp/docs/business-case/CommunityActivationProgram). Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

- Catena-X 
- https://catena-x.net/en/ 

repeat as necessary

UNTP Extensions

- [ ] Agriculture
- [ ] Critical Minerals
- [ X ] Textiles

### For Regulators

Please list any business registers, accreditations, certificates, licenses, or permits that you may implement as UNTP trust anchor functions. 

- Regulation name 
- Reference URL

repeat as necessary

### For Assurance Bodies

Type of Assurance body

- [ ] Standards Authority
- [ ] Industry Body
- [ ] Accreditation Authority
- [ ] Conformity Assessment Body (CAB)

Please list the relevant conformity schemes

Scheme name: 
Scheme reference URL:
Topic : (list relevant [conformity topics](https://test.uncefact.org/vocabulary/untp/core/0/conformityTopicCode))

repeat as necessary

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: VERA 
Product URL: https://vera.spherity.com/ 
Product major version: 
UNTP Specifications supported by this product:

repeat as necessary

### For Identity Registry Operators

Authoritative Registers of product, facility, or organisation identifiers may register their intent to implement the UNTP [Identity Resolver](https://uncefact.github.io/spec-untp/docs/specification/IdentityResolver) specification here.  

Register name: 
Register base URL:
Register Type : (products, locations, organisations, other)

# Other Relevant Information

Placeholder for any other relevant information that is not covered by the templated sections above.

**Comment by onthebreeze** [comment]
Thank you @RickySpherity - we will discuss this (and any others we get) at the next meeting late wednsday CET - see https://uncefact.github.io/spec-untp/docs/about/Meetings.  Join if you wish (dial-in details in the link).  It's the meeting optimised for US timezones so not very friendly for you in Europe.  Looking forward to working with Spherity as we progress through pilots towards stable release.

**Comment by onthebreeze** [comment]
Thank you for your commitment to implement UNTP.  Your entry is live at https://uncefact.github.io/spec-untp/docs/implementations/Software . If you would like further changes, please just add your comments to this ticket.  We will be in touch again when an implementation test suite is available.

**Comment by onthebreeze** [comment]
Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
