### ISSUE TITLE
Implementation registration for Government of British Columbia

### ISSUE THREAD

**Issue by PatStLouis** [uncefact/spec-untp#159]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

[Government of British Columbia](https://digital.gov.bc.ca) - [Energy and Mines Digital Trust](https://digital.gov.bc.ca/digital-trust/emdt/)

![bcgov_logo](https://github.com/user-attachments/assets/14aa6b34-aba3-48bf-93cc-fe1450cb05cd)
Registration country :  Canada
Operating countries : CA
Industry sectors : (list of [isic](https://unstats.un.org/unsd/classifications/Econ/isic) codes)

### Implementation statement

The BC government sees UNTP implementation as an opportunity to enable BC producers of raw materials to differentiate their products in emerging sustainability-focused markets, contributing to a sustainable, clean, secure, and fair global economy.

### Implementation Status

- [X] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ ] Digital Product Passport
- [ ] Digital Facility Record
- [ ] Digital Traceability Event
- [X] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [X] Pre-release pilot versions 0.x.x
- [X] Stable first release version 1.x.x

# Role Specific Information 

### For Regulators

Please list any business registers, accreditations, certificates, licenses, or permits that you may implement as UNTP trust anchor functions. 

- [Petroleum And Natural Gas Tenure](https://www2.gov.bc.ca/gov/content/industry/natural-gas-oil/petroleum-natural-gas-tenure)
- [Mine Permitting](https://www2.gov.bc.ca/gov/content/industry/mineral-exploration-mining/permitting)

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

[ACA-py](https://aca-py.org/latest/)
[Orgbook](https://orgbook.gov.bc.ca/)
[Traction](https://digital.gov.bc.ca/digital-trust/tools/traction/)

### For Identity Registry Operators

Authoritative Registers of product, facility, or organization identifiers may register their intent to implement the UNTP [Identity Resolver](https://uncefact.github.io/spec-untp/docs/specification/IdentityResolver) specification here.  

[Orgbook](https://orgbook.gov.bc.ca/)
Register Type : Organizations

# Other Relevant Information

**Comment by onthebreeze** [comment]
Thanks @PatStLouis !

**Comment by onthebreeze** [comment]
Thank you for your commitment to implement UNTP.  Your entry is live at 

- https://uncefact.github.io/spec-untp/docs/implementations/Software . 
- https://uncefact.github.io/spec-untp/docs/implementations/Regulators
- https://uncefact.github.io/spec-untp/docs/implementations/Registers

If you would like further changes, please just add your comments to this ticket.  We will be in touch again when an implementation test suite is available.
