### ISSUE TITLE
Implementation registration for software [FreshChain]

### ISSUE THREAD

**Issue by disruptiveapps** [uncefact/spec-untp#161]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : FreshChain Systems
Organisation homepage URL : https://freshchain.com.au
Logo (please attach approx 300x300px png logo to this issue)
![FreshChain-Square-300x300](https://github.com/user-attachments/assets/b1dfd9f3-f75c-457c-b649-1fac42c1aa91)

Registration country : Australia
Operating countries : Global
Industry sectors : J5829, H5229, N7020, O8292 

### Implementation statement

FreshChain is a fully integrated, blockchain enabled, paddock to plate assurance system that verifies the food you eat. It uses artificial intelligence, machine learning and deep learning algorithms to trace and monitor products throughout the supply chain. 

The protocol supports our values of ensuring that food is safe, secure, and sustainable. It enables quality data sharing that streamlines ESG responsiblities and assists with market access. UNTP is an important implementable standard for FreshChain to empower our customers to connect into global transparent and sustainable supply chains. 

### Implementation Status

- [x] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [x] Digital Facility Record
- [x] Digital Traceability Event
- [x] Digital Conformity Credential
- [x] Digital Identity Resolver
- [x] Decentralised Access Control
- [x] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: FreshChain Platform
Product URL: https://freshchain.com.au
Product major version: 2.3
UNTP Specifications supported by this product:
- [x] Digital Product Passport
- [x] Digital Facility Record
- [x] Digital Traceability Event
- [x] Digital Conformity Credential
- [x] Digital Identity Resolver
- [x] Decentralised Access Control

**Comment by onthebreeze** [comment]
Thank you for your commitment to implement UNTP.  Your entry is live at https://uncefact.github.io/spec-untp/docs/implementations/Software . If you would like further changes, please just add your comments to this ticket.  We will be in touch again when an implementation test suite is available.

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
