### ISSUE TITLE
Implementation registration for software [Tilkal]

### ISSUE THREAD

**Issue by sgaide** [uncefact/spec-untp#162]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Tilkal
Organisation homepage URL : https://www.tilkal.com
Logo (please attach approx 300x300px png logo to this issue)
Registration country : France
Operating countries : global
Industry sectors : A, B, C (exept C18, C2396), G, H

### Implementation statement

Tilkal is a premier platform for supply chain traceability and transparency, integrating a B2B blockchain network with advanced analytics and risk scoring algorithms to deliver a secure, real-time view of the end-to-end supply chain. Trusted by companies across industries, Tilkal collects and consolidates operational, social & environmental data to prove origin and impact from raw materials to end products, supporting DPP creation and compliance assurance.

### Implementation Status

- [x] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [ ] Digital Facility Record
- [ ] Digital Traceability Event
- [ ] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Tilkal
Product URL: https://www.tilkal.com
Product major version: n/a
UNTP Specifications supported by this product: DPP (planned)

![H_Pastille Rose - Typo Bleue  (1)](https://github.com/user-attachments/assets/77f1e186-6a93-46e9-addd-14011b8c58d8)

**Comment by onthebreeze** [comment]
Thank you for your commitment to implement UNTP.  Your entry is live at https://uncefact.github.io/spec-untp/docs/implementations/Software . If you would like further changes, please just add your comments to this ticket.  We will be in touch again when an implementation test suite is available.

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
