### ISSUE TITLE
Implementation registration for software [Northern Block]

### ISSUE THREAD

**Issue by mathieuglaude** [uncefact/spec-untp#163]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Northern Block
Organisation homepage URL : https://northernblock.io/
Logo (please attach approx 300x300px png logo to this issue)
![Northern-Block-Full-Logo](https://github.com/user-attachments/assets/76c05998-3da2-48d0-965b-33bb946eb8ab)

Registration country : Canada
Operating countries : Canada
Industry sectors : Section J: Information and Communication

### Implementation statement

Our enterprise digital credentialing product enables the mining industry to exchange verifiable sustainability data based on industry standards, such as [Towards Sustainable Mining](https://mining.ca/towards-sustainable-mining/). As these standards are key indicators of sustainable mining practices, it's essential that they can be easily integrated into digital product passports.

### Implementation Status

- [x] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ ] Digital Product Passport
- [ ] Digital Facility Record
- [ ] Digital Traceability Event
- [x] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Please list any industry associations of which you are a member and which may be a focal point for a UNTP [community activation program](https://uncefact.github.io/spec-untp/docs/business-case/CommunityActivationProgram). Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

- [Towards Sustainable Mining](https://mining.ca/towards-sustainable-mining/)
- [The Copper Mark](https://coppermark.org/)

UNTP Extensions

- [ ] Agriculture
- [x] Critical Minerals
- [ ] Textiles

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

[Northern Block's Orbit Enterprise](https://northernblock.io/orbit-enterprise)
[ACA-Py](https://github.com/hyperledger/aries-cloudagent-python)
[Northern Block's Trust Registry Service](https://humantrust.ca/)

# Other Relevant Information

**Comment by onthebreeze** [comment]
Thank you for your commitment to implement UNTP.  Your entry is live at https://uncefact.github.io/spec-untp/docs/implementations/Software . If you would like further changes, please just add your comments to this ticket.  We will be in touch again when an implementation test suite is available.

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
