### ISSUE TITLE
ConformityAttestation.attestationDescription Missing from 0.3.10 context file. 

### ISSUE THREAD

**Issue by Jsyro** [uncefact/spec-untp#164]
### Impacted sections

List UNTP specification page(s) that are impacted by this issue.  Eg

 - https://uncefact.github.io/spec-untp/docs/specification/DigitalConformityCredential

### Issue Description
Jargon defines a `attestationDescription` attribute, https://jargon.sh/user/unece/ConformityCredential/v/0.3.10/artefacts/readme/render#conformityattestation

That is not found in the published context file. https://test.uncefact.org/vocabulary/untp/dcc/0/untp-dcc-context-0.3.10.jsonld

**Comment by onthebreeze** [comment]
Thanks - that's a bug.  Fixed in the latest raw version and will consequently be fixed in the next release. https://jargon.sh/user/unece/untp-core/v/working/artefacts/jsonldContexts/untp-core.jsonld?class=untp-core
