### ISSUE TITLE
Implementation registration for software [ReLOG3P]

### ISSUE THREAD

**Issue by ReLOG3PSNE** [uncefact/spec-untp#166]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : ReLOG3P SRL
Organisation homepage URL : https://relog3p.com/
Logo (please attach approx 300x300px png logo to this issue)
![Logo full con scritta_Compr1](https://github.com/user-attachments/assets/e081319f-e40e-4638-8353-af1278e64c4e)
Registration country : Italy
Operating countries : Global
Industry sectors : Other support activities for transportation 

### Implementation statement

ReLOG3P is an Innovative Startup and Benefit Corporation based in Italy founded with the specific aim to support the Global Trade to contribute, among others, achieving the UN Agenda 2030 and its Sustainable Development Goals as well as the EU objectives set by the Green Deal, Fit for 55% Package, Sustainable and Smart Mobility Strategy, Digital Strategy.
Full transparency all along the Supply Chains is key to achieve our targets, and UNTP vision and mission are extremely aligned to ours, specifically looking at scaling the transparency around Sustainability and against any type of fake and washing, and we strive to embrace and embed it fully within our own product, services and actions.

### Implementation Status

- [x] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [ ] Digital Facility Record
- [x] Digital Traceability Event
- [ ] Digital Conformity Credential
- [x] Digital Identity Resolver
- [x] Decentralised Access Control
- [x] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Please list any industry associations of which you are a member and which may be a focal point for a UNTP [community activation program](https://uncefact.github.io/spec-untp/docs/business-case/CommunityActivationProgram). Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

- Association name
- Association homepage URL

repeat as necessary

UNTP Extensions

- [ ] Agriculture
- [ ] Critical Minerals
- [ ] Textiles

### For Regulators

Please list any business registers, accreditations, certificates, licenses, or permits that you may implement as UNTP trust anchor functions. 

- Regulation name 
- Reference URL

repeat as necessary

### For Assurance Bodies

Type of Assurance body

- [ ] Standards Authority
- [ ] Industry Body
- [ ] Accreditation Authority
- [ ] Conformity Assessment Body (CAB)

Please list the relevant conformity schemes

Scheme name: 
Scheme reference URL:
Topic : (list relevant [conformity topics](https://test.uncefact.org/vocabulary/untp/core/0/conformityTopicCode))

repeat as necessary

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: ReACT
Product URL: https://react.relog3p.com/
Product major version: 
UNTP Specifications supported by this product: Architecture, Digital Product Passport, Digital Traceability Events

Product name: SRL®
Product URL: https://react.relog3p.com/srl
Product major version: 
UNTP Specifications supported by this product: Architecture, Digital Product Passport, Digital Traceability Events, Sustainability Vocabulary Catalog

### For Identity Registry Operators

Authoritative Registers of product, facility, or organisation identifiers may register their intent to implement the UNTP [Identity Resolver](https://uncefact.github.io/spec-untp/docs/specification/IdentityResolver) specification here.  

Register name: 
Register base URL:
Register Type : (products, locations, organisations, other)

# Other Relevant Information

ReLOG3P’s manifesto is the development of “Innovation 4 Good”, Responsible & Ethical, Values & Purpose-Based, Trustworthy, Democratic, Agnostic, Agile, Modular and Scalable, (cyber)Secure & Privacy principles, by default and by design, of the technologies typical of the 4th Industrial Revolution (AI, Data Science, Blockchain, quantum computing, etc.).
For the purpose of reaching its targets, ReLOG3P built ReACT - ReAccompanying Chain Transformation - a SLaaS platform – Sustainable Logistics as a Service - and a complete Virtual Control Tower for Global Trade allowing companies to measure, monitor, visualize, report and improve, in continuous, real time & predictive manner, their progress towards social, environmental and economic Sustainability by using a powerful, truly end-to-end integrated & middleware platform.
The main tool of ReACT is SRL® – SDG Readiness Level – a trademarked tool to, measure, monitor, visualize, report and improve, in continuous, real time & predictive manner the progress towards social, environmental and economic Sustainability, specifically designed for, but not limited to, the Global Trade (Logistics, Supply Chains, Mobility and Transport industries).
SRL® consider Scope 1-2-3 environmental, social & economic Sustainability, transparency, track & trace along the entire chain and encompasses and aggregates over 80 different Sustainability measuring, monitoring and reporting standards, frameworks and tools available internationally into a unique, simple to use, easy to read tool, via its data science-based tools (not limited to Artificial Intelligence and Machine Learning), used in an Agnostic, Responsible and Ethic, Transparent, Trustworthy manner.
SRL® is a powerful data-based, scientific and objective tool to increase Compliance, Reputation, Awareness, Engagement and avoid greenwashing, frauds & counterfeiting claims on Sustainability.

**Comment by onthebreeze** [comment]
Thank you for your registration. We will review it at the next team meeting on Thursday

**Comment by ReLOG3PSNE** [comment]
[like]  Stefano Negrini reacted to your message:
________________________________

**Comment by ReLOG3PSNE** [comment]
@onthebreeze , I have integrated the missing info, good for the publishing! Txs

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
