### ISSUE TITLE
Implementation registration for software [Lumoin/Verifable]

### ISSUE THREAD

**Issue by veikkoeeva** [uncefact/spec-untp#170]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Lumoin
Organisation homepage URL : https://lumoin.com
Logo (please attach approx 300x300px png logo to this issue)
![logo](https://github.com/user-attachments/assets/3deae657-3983-4ee1-a615-13edadf0cd4c)

Registration country : Finland
Operating countries : global
Industry sectors :  [J - Information and communication](https://unstats.un.org/unsd/classifications/Econ/Structure/Detail/EN/27/J)

### Implementation statement

**Lumoin** builds Verifable and open-source components to drive the transition to a regenerative and circular economy by implementing the UN Transparency Protocol (UNTP). Verifable offers secure management of Digital Product Passports (DPPs) and verifiable credentials, creating accountable, dependable pathways for supply-chain and project finance across global value chains. Focusing on habitats' resilience, we ensure that materials, water, and energy flow sustainably through societies. By leveraging UNTP, Verifable empowers individuals and businesses to co-create meaningful, accountable choices, driving regenerative and sustainable actions for a better future.

### Implementation Status

- [x] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [x] Digital Facility Record
- [x] Digital Traceability Event
- [x] Digital Conformity Credential
- [x] Digital Identity Resolver
- [x] Decentralised Access Control
- [x] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Please list any industry associations of which you are a member and which may be a focal point for a UNTP [community activation program](https://uncefact.github.io/spec-untp/docs/business-case/CommunityActivationProgram). Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

- Association name
- Association homepage URL

repeat as necessary

UNTP Extensions

- [x] Agriculture
- [x] Critical Minerals
- [x] Textiles

### For Regulators

Please list any business registers, accreditations, certificates, licenses, or permits that you may implement as UNTP trust anchor functions. 

- Regulation name 
- Reference URL

repeat as necessary

### For Assurance Bodies

Type of Assurance body

- [ ] Standards Authority
- [ ] Industry Body
- [ ] Accreditation Authority
- [ ] Conformity Assessment Body (CAB)

Please list the relevant conformity schemes

Scheme name: 
Scheme reference URL:
Topic : (list relevant [conformity topics](https://test.uncefact.org/vocabulary/untp/core/0/conformityTopicCode))

repeat as necessary

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Verifiable
Product description: DID, VC and presentation methods and standards as open source
Product URL: https://github.com/Lumoin/Verifiable
Product major version: 
UNTP Specifications supported by this product:

Product name: CoreLoop
Product description: UNTP and other data shapes standards and transformations as open source
Product URL: https://github.com/Lumoin/CoreLoop
Product major version: 
UNTP Specifications supported by this product:

Product name: Verifable
Product description: UNTP and other related systems as a service to implement transition pathways to regenerative/circular economy globally
Product URL: https://verifable.app
Product major version: 
UNTP Specifications supported by this product:

repeat as necessary

### For Identity Registry Operators

Authoritative Registers of product, facility, or organisation identifiers may register their intent to implement the UNTP [Identity Resolver](https://uncefact.github.io/spec-untp/docs/specification/IdentityResolver) specification here.  

Register name: 
Register base URL:
Register Type : (products, locations, organisations, other)

# Other Relevant Information

Placeholder for any other relevant information that is not covered by the templated sections above.

**Comment by onthebreeze** [comment]
Thank you for your registration. We will review it at the next team meeting on Thursday

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
