### ISSUE TITLE
Implementation registration for software [Transmute]

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#171]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Transmute
Org id: did:web:transmute.industries
Organisation homepage URL : https://transmute.industries/
Logo 
![1-Mark-Dark](https://github.com/user-attachments/assets/146ec837-fb32-4181-a194-6dd8148c0b1f)

Registration country : US
Operating countries : Global
Industry sectors : Supply Chain

### Implementation statement

The Transmute platform offers key supply chain documents, and will add the UNTP schemas offering seamless industry uptake.

### Implementation Status

- [X] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [X] Digital Product Passport
- [X] Digital Facility Record
- [X] Digital Traceability Event
- [X] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [X] Pre-release pilot versions 0.x.x
- [X] Stable first release version 1.x.x

# Role Specific Information 

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Transmute
Product URL: https://platform.transmute.industries/
UNTP Specifications supported by this product: 0.3.10

**Comment by onthebreeze** [comment]
https://uncefact.github.io/spec-untp/docs/implementations/Software page updated.  Thank you for your commitments. Please re-open this ticket if there is something you wish to change on your registration.
