### ISSUE TITLE
Implementation registration for software [TBA]

### ISSUE THREAD

**Issue by abhishekmaha23** [uncefact/spec-untp#179]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Quintessence Research B.V.
Organisation homepage URL : https://quintessenceresearch.com/
Logo (please attach approx 300x300px png logo to this issue)
![FF_QUINTESENCE_icon](https://github.com/user-attachments/assets/846cd606-59ba-46b9-9930-b08b09b4380a)

Registration country : Netherlands
Operating countries : global
Industry sectors : 6219, 5829

### Implementation statement

Quintessence Research is a consultancy dedicated to bridging the gap between fundamental research and industrial applications. We partner with companies, research institutes, and academic institutions to address real-world challenges, identify opportunities, and implement cutting-edge solutions that align with human-centered ideals. Our expertise spans Next-Gen Internet, Sustainability, and Smart Industry, along with the emerging technologies that support these areas.

Our goal is to deliver end-to-end solutions aligned with Circular Economy standards, covering the entire lifecycle—from mining and processing to logistics and Re-X processes—designed to extend product life and optimize the use of critical resources. We focus on building software components that are easy to adopt, minimize redundant data replication, and remain adaptable to the needs of SMEs across diverse manufacturing sectors.

### Implementation Status

- [X] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [X] Digital Product Passport
- [X] Digital Facility Record
- [X] Digital Traceability Event
- [X] Digital Conformity Credential
- [X] Digital Identity Resolver
- [X] Decentralised Access Control
- [X] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [ ] Pre-release pilot versions 0.x.x
- [X] Stable first release version 1.x.x

# Role Specific Information 

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: to-be-announced (TBA)
Product URL: 
Product major version: 
UNTP Specifications supported by this product:

**Comment by onthebreeze** [comment]
Thank you for your expression of intent.  However it appears that you are a consultancy rather than a product vendor.  At present we are not registering consultancies.  Kind regards

**Comment by abhishekmaha23** [comment]
Actually, a consultancy with the vision/ambition to become a product vendor. 
The specifications (and thus, the business models) for DPPs and DPP service vendors are still evolving, and so we're initially positioning ourselves as a consultancy to help clarify the domain better. We still intend to build a platform, as clearer standards emerge and get adopted. I could update the description?

**Comment by onthebreeze** [comment]
Understood.  We did have a discussion about whether to include consultancies on the list but collectively agreed that it is better not to do so because there's no easy way to verify. That decision included many people who are themselves consultancies.  A software product either conforms to the specification or it doesn't.  Consultancies are more tricky.  

So we welcome your commitment to UNTP but would request that you re-register when you have a product to test.
