### ISSUE TITLE
Conformity Credential Data Model

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/spec-untp#18]
Our first go at a conformity credential has been through both a real world pilot (Australian red meat industry) and also a forensic analysis by another UN project team (Digital Product Conformity Credential Exchange or DPCCE) that has the global experts on this stuff.  The result is an upgraded data model - 

https://jargon.sh/user/unece/ConformityCredential/v/working/artefacts/readme/render

Lets get UNTP team feedback on this and then lets make a v0.2 release and update the published UNTP site.

**Comment by JohnOnGH** [comment]
Spotted a minor type: "batttery" - just proving I've been to the page!

More substantively, I think that adding "jurisdiction" to the model will be valuable for international use cases. The reason being that this gives the legal context in which the authority has (or claims) authority. While most of our concerns will/should be solved by reference to international standards, some will be national and the "sovereign risk" associated with some jurisdictions varies and is part of the consideration for any supply chain.

In terms of where/how perhaps "Jurisdiction" is another field in the Authority structure, and in terms of values, we could/should use international country and state based codes. [haven't thought too long on this though]

**Comment by onthebreeze** [comment]
Will create PR for this.
