### ISSUE TITLE
Implementation registration for software cordina.io

### ISSUE THREAD

**Issue by nickcordina** [uncefact/spec-untp#182]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Cordina.io
Organisation homepage URL :www.cordina.io
Logo ![Logo-Full-Colour-Forrest-Green-Background- Medium](https://github.com/user-attachments/assets/46e2b567-7cd3-4375-b0f9-aa9f97043483)
Registration country : Australia
Operating countries : Global
Industry sectors : B09

### Implementation statement

Cordina is implementing UNTP to help simplify ESG disclosures for Heavy Industry and delivery high value interactive benchmarking.  Approx 100 words / 500 characters.

### Implementation Status

- [ X] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ ] Digital Product Passport
- [ ] Digital Facility Record
- [X] Digital Traceability Event
- [X] Digital Conformity Credential
- [X] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [X] Pre-release pilot versions 0.x.x
- [X] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

UNTP Extensions

- [ ] Agriculture
- [X] Critical Minerals
- [ ] Textiles

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Knime 
Product URL: https://www.knime.com/
Product major version: 5.2.5
UNTP Specifications supported by this product: TBC

**Comment by onthebreeze** [comment]
Thank you for your registration of intent.  Will prepare site update shortly.

**Comment by nickcordina** [comment]
[like]  Nicholas Smith reacted to your message:
________________________________

**Comment by onthebreeze** [comment]
You registration is live at https://uncefact.github.io/spec-untp/docs/implementations/Software/#cordina 

Thank you for your commitment.  Closing this issue - but please re-open it to request any fixes and to register your tested implementation (test suite and reference implementation will be announced soon)
