### ISSUE TITLE
Implementation registration for software Transmute

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#184]
# General Information 
This is to bump up from commitment to actual support. Please refer to  see https://github.com/uncefact/spec-untp/issues/171 for background.

### Implementation statement

Direct links to implementations: 

- DPP: https://platform.transmute.industries/templates/urn:transmute:template:untp-dpp
- DCC: https://platform.transmute.industries/templates/urn:transmute:template:untp-dcc
- DFP: https://platform.transmute.industries/templates/urn:transmute:template:untp-dfr
- DTE: https://platform.transmute.industries/templates/urn:transmute:template:untp-dte

### Implementation Status

- [ ] Registration of commitment to implement 
- [x] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [x] Digital Facility Record
- [x] Digital Traceability Event
- [x] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [ ] Stable first release version 1.x.x

**Comment by onthebreeze** [comment]
Well done!  Will update live site shortly.  Please update this ticket when your have upgraded to v0.5.0.
