### ISSUE TITLE
Implementation registration for software The Copper Mark

### ISSUE THREAD

**Issue by EFalconerCM** [uncefact/spec-untp#186]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : The Copper Mark
Organisation homepage URL : https://coppermark.org
Logo (please attach approx 300x300px png logo to this issue)
Registration country : United Kingdom
Operating countries : global
Industry sectors : 0729, 2420
![01_Copper Mark_logo_RGB_Primary](https://github.com/user-attachments/assets/dba5a09e-8868-49a8-9d0a-1ebe2a73cc5a)

### Implementation statement

The Copper Mark is the leading assurance framework promoting responsible practices in the copper, molybdenum, nickel, and zinc value chains. It intends to implement the UNTP to support the piloting of a full value chain approach, promoting transparency and ensuring the highest levels of integrity in their standards.

### Implementation Status

- [x] Registration of commitment to implement 

- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [ ] Digital Product Passport
- [ ] Digital Facility Record
- [ ] Digital Traceability Event
- [x] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [ ] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [ ] Stable first release version 1.x.x

# Role Specific Information 

### For Assurance Bodies

Type of Assurance body

- [x] Standards Authority
- [ ] Industry Body
- [ ] Accreditation Authority
- [ ] Conformity Assessment Body (CAB)

Please list the relevant conformity schemes

Scheme name: Risk Readiness Assessment 
Scheme reference URL: https://coppermark.org/wp-content/uploads/2023/10/RRA-v3.0-Criteria-Guide_2023.pdf
Topic : environment.emissions environment.waste environment.water governance.compliance social.community social.labour social.rights

Scheme name: Joint Due Diligence Standard for Copper, Lead, Molybdenum, Nickel and Zinc
Scheme reference URL: https://coppermark.org/wp-content/uploads/2024/08/Joint-Due-Diligence-Standard_v3_26AUG22Clean.pdf
Topic: governance.transparency

Scheme name: The Copper Mark Chain of Custody Standard
Scheme reference URL: https://coppermark.org/wp-content/uploads/2022/06/The-Copper-Mark_Chain-of-Custody-Standard_FINAL_1Jul2022.pdf
Topic: governance.transparency

**Comment by onthebreeze** [comment]
Thank you for your registration of intent.  Will prepare site update shortly.

**Comment by onthebreeze** [comment]
Your registration is live at https://uncefact.github.io/spec-untp/docs/implementations/Certifiers#the-copper-mark

Thank you for your commitment.  Closing this ticket but please re-open it if you need to make any corrections or to register your tested implementation (note that test suite and reference implementation will be announced soon).
