### ISSUE TITLE
Upgrade docusaurus

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/spec-untp#189]
### Impacted sections

All

### Issue Description

Please upgrade docusaurus to the latest stable version

**Comment by onthebreeze** [comment]
is this done?

**Comment by webilhan** [comment]
@onthebreeze For some reasons I've missed an email notification about this ticket. Will work on it

**Comment by webilhan** [comment]
I've upgraded docusaurus to the latest stable verions, here is PR - https://github.com/uncefact/spec-untp/pull/204
@kshychko Please check and approve it. I can't merge it without approve.
