### ISSUE TITLE
Implementation registration for software Enigio trace:original

### ISSUE THREAD

**Issue by goranalmgren-enigio** [uncefact/spec-untp#191]
Please complete the General Info section and then the relevant Specific Info section that matches your role (delete specific sections that are not relevant).

# General Information 

### Organisation data

Organisation name : Enigio
Organisation homepage URL : https://enigio.com/
Logo (please attach approx 300x300px png logo to this issue)
[enigio-logo-midnight-blue.pdf](https://github.com/user-attachments/files/17325324/enigio-logo-midnight-blue.pdf)

Registration country : Sweden
Operating countries :  Global
Industry sectors : "6209","Other information technology and computer service activities"

### Implementation statement
Recent legislation has paved the way for complete trade digitalisation. Achieving seamless end-to-end digitalisation also requires that trading parties can exchange structured data across multiple systems efficiently. Without such capabilities, the risk of fragmentation increases, leading to multiple platforms and/or complex API integrations.
Enigio's trace:original offers a solution that creates freely transferable electronic original documents wich includes structured data. This allows any recipient of a trace:original document to extract verified structured data effortlessly, without the need for onboarding or additional system integration.

### Implementation Status

- [ ] Registration of commitment to implement 
- [ ] Registration of tested implementation (attach test evidence)

### Implementation Scope

Select the UNTP specification items that you plan to implement / have implemented

- [x] Digital Product Passport
- [x] Digital Facility Record
- [x] Digital Traceability Event
- [x] Digital Conformity Credential
- [ ] Digital Identity Resolver
- [x] Decentralised Access Control
- [ ] Sustainability Vocabulary Profile

Select the UNTP specification version(s) that you plan to support

- [x] Pre-release pilot versions 0.x.x
- [x] Stable first release version 1.x.x

# Role Specific Information 

### For Industry 

Please list any industry associations of which you are a member and which may be a focal point for a UNTP [community activation program](https://uncefact.github.io/spec-untp/docs/business-case/CommunityActivationProgram). Also please indicate which (if any) [UNTP industry extensions](https://uncefact.github.io/spec-untp/docs/extensions/) you plan to implement

- Association name
- Association homepage URL

repeat as necessary

UNTP Extensions

- [ ] Agriculture
- [ ] Critical Minerals
- [ ] Textiles

### For Regulators

Please list any business registers, accreditations, certificates, licenses, or permits that you may implement as UNTP trust anchor functions. 

- Regulation name 
- Reference URL

repeat as necessary

### For Assurance Bodies

Type of Assurance body

- [ ] Standards Authority
- [ ] Industry Body
- [ ] Accreditation Authority
- [ ] Conformity Assessment Body (CAB)

Please list the relevant conformity schemes

Scheme name: 
Scheme reference URL:
Topic : (list relevant [conformity topics](https://test.uncefact.org/vocabulary/untp/core/0/conformityTopicCode))

repeat as necessary

### For Software Solutions

Please list your software products and major versions that you wish to register for UNTP implementation

Product name: Enigio trace:original
Product URL: https://enigio.com/traceoriginal/
Product major version: 3.0
UNTP Specifications supported by this product: The solution offers "containers" for structured data that are freely transferable. The containers supports any specification, allowing data to be populated flexibly within the container. 

repeat as necessary

### For Identity Registry Operators

Authoritative Registers of product, facility, or organisation identifiers may register their intent to implement the UNTP [Identity Resolver](https://uncefact.github.io/spec-untp/docs/specification/IdentityResolver) specification here.  

Register name: 
Register base URL:
Register Type : (products, locations, organisations, other)

# Other Relevant Information

Placeholder for any other relevant information that is not covered by the templated sections above.

**Comment by onthebreeze** [comment]
You registration is live at https://uncefact.github.io/spec-untp/docs/implementations/Software/#enigio

Thank you for your commitment.  Closing this issue - but please re-open it to request any fixes and to register your tested implementation (test suite and reference implementation will be announced soon)
