### ISSUE TITLE
Heading IDs

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#205]
### Impacted sections

 - https://uncefact.github.io/spec-untp/docs/specification/VerifiableCredentials

### Issue Description

Really minor thing but for some reason, the usual heading IDs aren't working so that, for example, I can't link directly to the Basic Profile at https://uncefact.github.io/spec-untp/docs/specification/VerifiableCredentials. I'd really like to be to able to do that as I refer to that specific section frequently. Looks like a minor bug in the Docusaurus set up or something??

**Comment by onthebreeze** [comment]
Fixed - for example https://uncefact.github.io/spec-untp/docs/specification/VerifiableCredentials#vcdm-profile
