### ISSUE TITLE
RBA UNTP Extension

### ISSUE THREAD

**Issue by jcutts-RBA** [uncefact/spec-untp#209]
Extension Name:
Responsible Business Transparency Protocol (RBTP)
 
Extension Owner:
The Responsible Business Alliance 
 
Geographic Scope:
Global
 
Industry Scope:
Electrical, Electronic and Automotive Parts
 
Extension Link:
TBD
 
Extension Launched:
Nov 2024
 
Logo:
Responsible Business Alliance
 
Implementation Statement:
The Responsible Business Alliance (RBA) is a coalition of companies driving sustainable value for workers, the environment and business throughout the global supply chain.  Our members, suppliers and stakeholders collaborate to improve working and environmental conditions and business performance through leading standards and practices. Transparency and traceability in value chains is key to building confidence and value of sustainable business practices. Accordingly, the RBA is pleased to build upon the foundational capabilities provided by the UN Transparency Protocol (UNTP) to deliver a suite of interoperability standards for the electrical and electronic goods and automotive parts industries. 
 
Credential Extension:
Credential:    Responsible Minerals Initiative Credential (RMIC)
Description:  A conformity credential attesting to the responsible sourcing of minerals in supply chains.
Extension of:  Digital Conformity Credential

Credential:    Responsible Labour Initiative Credential (RLIC)
Description:  A conformity credential attesting that the rights of workers vulnerable to forced labor in global supply chains are consistently respected and promoted.
Extension of:  Digital Conformity Credential

Credential:    Responsible Factory Initiative Credential (RFIC)
Description:  A conformity credential attesting that a supplier facility meets the RBA Code of practice.
Extension of:  Digital Conformity Credential

Credential:    Responsible Environment Initiative Credential (REIC)
Description:  A conformity credential attesting to the performance of a facility in the areas of Decarbonization, Chemical Management, Water Stewardship, and Circular Materials 
Extension of:  Digital Conformity Credential

Credential:    Electrical Goods Passport (EGP)
Description:  A digital product passport tailored to the needs of electrical and electronic products and their conformity to Environmental, Social, and Governance standards.
Extension of:  Digital Product Passport

Credential:   Digital Battery Passport (DBP)
Description:  A digital product passport that is designed to meet the needs of RBA members whilst also offering compliance with emerging EU standards.
Extension of:  Digital Product Passport

Credential:    Electrical Facility Record (EFR) 
Description:  A digital facility record tailored to the needs of manufacturing facilities in the electrical and electronic industry sectors and their sustainability performance. 
Extension of:  Digital Facility Record

**Comment by onthebreeze** [comment]
Registration is recorded in PR #210 - should be merged soon.

**Comment by onthebreeze** [comment]
Thank you for your commitment - your entry is live at https://uncefact.github.io/spec-untp/docs/extensions/ExtensionsRegister#responsible-business-transparency-protocol 

Please re-open this ticket to make any corrections or update status.
