### ISSUE TITLE
Implementation registration for UDP for the Global Built Environment

### ISSUE THREAD

**Issue by GiacomettiW17** [uncefact/spec-untp#211]
Intent to Extend UNTP

Extension Name:
UDP for the Global Built Environment

Extension Owner:
Standards Australia and the International Code Council

Geographic Scope:
Global

Industry Scope:
Built Environment 

Extension Link:
TBD

Extension Launched:
Nov 2024

Logo:
![SA and ICC](https://github.com/user-attachments/assets/b3c6ce66-01a3-494b-9390-0d74ed0c294e)

 
Implementation Statement:
The UDP is an extension of the UNTP and is seeking to leverage its decentralised framework to provide transparent, trustworthy, and verifiable data in the global built environment. The UDP is an open protocol that will allow for the efficient exchange of verifiable data, enhancing reporting and compliance across jurisdictions and life cycle stages. This project seeks to improve the interoperability of data across the built environment, aiming to make reporting more cost effective, accurate and efficient for all stakeholders.

Credential Extension:
Credential:    Sustainability Vocabulary Catalogue
Description:  The UDP is a global extension of the SVC for the global built environment
Extension of:   SVC

**Comment by onthebreeze** [comment]
Thanks you - this request is reflected in PR #210 and should be merged tomorrow.

**Comment by onthebreeze** [comment]
Thank you for your commitment - your entry is live at https://uncefact.github.io/spec-untp/docs/extensions/ExtensionsRegister#udp-for-the-global-built-environment

Please re-open this ticket to make any corrections or update status.

**Comment by GiacomettiW17** [comment]
Hi @onthebreeze could I request one edit for the implementation summary? In the first line can we please use the UDP in full instead of acronym? e.g. The Universal Data Protocol (UDP) is an extension of the UNTP and is seeking to....

It will help explain the UDP for those who are not across the project.  

Thanks,
Will Giacometti

**Comment by onthebreeze** [comment]
Done - https://uncefact.github.io/spec-untp/docs/extensions/ExtensionsRegister/#universal-data-protocol-for-the-global-built-environment
