### ISSUE TITLE
Enhance Jargon.sh UML Diagrams to Indicate Required Fields

### ISSUE THREAD

**Issue by ashleythedeveloper** [uncefact/spec-untp#215]
### Impacted sections

 - https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport
 - https://uncefact.github.io/spec-untp/docs/specification/ConformityCredential
 - https://uncefact.github.io/spec-untp/docs/specification/DigitalTraceabilityEvents
 - https://uncefact.github.io/spec-untp/docs/specification/DigitalFacilityRecord
 - https://uncefact.github.io/spec-untp/docs/specification/DigitalIdentityAnchor

### Issue Description

As a Business Analyst,
I want the UNTP UML diagrams in Jargon.sh to clearly indicate which fields are required for each Object type,
So that I can more easily perform data mapping and credential building without needing to reference technical schema files.

Acceptance Criteria:
- [x] Review the current UNTP UML diagram generation process in Jargon.sh
- [x] Develop a visual indicator system for required fields in UML diagrams (e.g., asterisk, bold text, or other clear visual marker)
- [x] Update UML diagram generation to include required field indicators based on data model specifications
- [ ] Apply updates to all existing UML diagrams in UNTP core data models

I don't feel this is the right place for this ticket, but I need to store it somewhere to track this issue/visibility.

**Comment by colugo** [comment]
Hi @ashleythedeveloper I made this change in Jargon a little while ago, and it's now live. Next time those domains are changed and released, jargon's webhook will provide new diagrams to the github actions script.

![image](https://github.com/user-attachments/assets/0c1fad59-6b11-43e9-9442-5316165bc88e)

Here's a link to one of the domains that shows what this looks like:

https://jargon.sh/user/unece/DigitalProductPassport/v/working/artefacts/diagram/render.svg?light=true

**Comment by onthebreeze** [comment]
looks like this is done.
