### ISSUE TITLE
Single page spec

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#3]
I recommend we drop the multi-page "web site" approach and condense everything into a single page. That's how technical specifications are typically organized; and for a good reason, it makes it much clearer what's the concise scope of the recommendation.

**Comment by onthebreeze** [comment]
I think a page per spec is a good idea - but there's actually a collection of related bu independent specs here.  So I think better to have a page for each spec.

**Comment by onthebreeze** [comment]
based on the conversation last meeting, I think we can close this one.  There are a number of specs and each one has a single page.
