### ISSUE TITLE
Refer to ISO/IEC 18975 rather than GS1 Digital Link?

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#33]
There are various references to GS1 Digital Link in the doc. For example on the [opening page](https://uncefact.github.io/spec-untp/docs/specification#data-carriers) where it says "...Therefore, the UNTP defines a generalised protocol (based on [GS1 digital link](https://www.gs1.org/standards/gs1-digital-link)) to allow any identifier scheme (GS1 or otherwise) to be consistently resolvable..."

GS1 Digital Link itself *is* limited to GS1 IDs, However, [ISO/IEC DIS 18975](https://www.iso.org/standard/85540.html) offers a more general framework that covers two alternative high level URI structures and, optionally, tying those URIs to Linksets available via a resolver that reacts to the `linkType` parameter. GS1 Digital Link conforms to ISO/IEC 18975.

**Caution** ISO/IEC 18975 is currently a [Draft International Standard](https://www.iso.org/stages-and-resources-for-standards-development.html) with voting open until 2024-04-24. The expected path is that it will become a Final Draft International Standard later this year and a full standard in January 2025. Of course that timeline may not happen and comments received may result in significant changes.

Even so, it seems that the ISO/IEC standard is a better reference for UNTP *except* where the discussion is specifically about GS1 Digital Link. It might be appropriate in some places to talk about "identification and resolution schemes that conform to ISO/IEC 18975, such as GS1 Digital link"

**Comment by zachzeus** [comment]
Agreed - I'm happy to go through the docs and build a pull request to apply this across the docs.  Will work on it this weekend (unless someone beats me to it.).

**Comment by onthebreeze** [comment]
Phil beat you to it - he has raised a PR #34 which looks good to me.

**Comment by zachzeus** [comment]
Closed by PR #34 ?
