### ISSUE TITLE
Is circularity in scope?

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#35]
The UNTP work focuses on sustainable supply chains, fighting counterfeit goods etc. But I don't see any reference to circularity, i.e. whether goods re repairable, recyclable or whatever. Is this in scope? If so, I think we'll need to make that clear somehow. If not, OK, understood.

**Comment by zachzeus** [comment]
Circularity has come up in the UNCRM project (which we're in the process of refactoring to be an extension of UNCRM).  I think it probaby fits better here.  I'll pull that commentary from there and propose some change here.

**Comment by onthebreeze** [comment]
I think the answer has to be YES.  But there remains a design question about where circularity concerns impact our work.  I think the most obvious place is in the sustainability vocabularies https://uncefact.github.io/spec-untp/docs/specification/Vocabularies where I see circularity semantics are part of the sustainability vocabulary / topic map.  

I'm not sure whether we should have circularity specific attributes in the DPP schema.  Ie do we have an actual schema property like "RecycledContentPercentage" ?  Or just re-use the sustainability claim structure where the topic is something like vocabulary.uncefact.org/sustainability/recycledContent?  

Thoughts?

**Comment by zachzeus** [comment]
Another way to think about this is what is the 'top' level circularity topics vs industry or region specific extensions.  For example "Circularity" for the mushroom industry would be completely different from the auto manufacturing industry.  So what are the UNTP level circularity attributes that support general adoption, but enables unique implementations.

This leads me to agree with @onthebreeze that the sustainability vocabularies are the best place.  We expect there to be lots of variability here.

**Comment by ReLOG3PSNE** [comment]
All, in fact in the Rec49 preparation we did already include the subject of circularity in the 2.5 paragraph.
Specifically, we indeed have indicated that:

- The UNTP will not duplicate existing work but rather will work to ensure alignment (i.e. with UN/CEFACT product circularity data use case and ISO-59040 product circularity data sheet) by specifying standardised language for circularity criteria for use in UN Digital Product Passports  and UN Digital Product Conformity Credentials
- The UNTP sustainability vocabulary  will align with existing UN and ISO standards for product circularity claims

Thus, I also do align with your comments above and suggest to embed this matter into the issue #12 sustainability vocabularies !

**Comment by philarcher** [comment]
This seems well taken care of. Propose this issue be closed.
