### ISSUE TITLE
Add PDF generator capability

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/spec-untp#40]
Sometimes it'll be useful to generate a PDF document version of the site.  

https://github.com/jean-humann/docs-to-pdf seems like a plausible solution.  What do you think @webilhan ?

**Comment by nissimsan** [comment]
What is the status of this? What are the actions to close the issue?

**Comment by nissimsan** [comment]
I suggest File -> Print -> Print as PDF

**Comment by onthebreeze** [comment]
looks like it's working (assuming you notice the tiny little "PDF" bottom right.  Suggestions:

* Make the PDF print option on the footer a little more obvious "Print this specification as PDF" 
* Add a exclusion list to exclude
 * https://uncefact.github.io/spec-untp/docs/about/Meetings
 * https://uncefact.github.io/spec-untp/docs/about/FAQ

**Comment by kshychko** [comment]
@onthebreeze

- [ ] _Make the PDF print option on the footer a little more obvious "Print this specification as PDF"_ - done
- [ ] _If possible, also add a "Print as PDF" on each page where the button only prints that page. Then there's the footer for the whole thing and also page level option._ - @webilhan and me will look into this
- [ ] _Add a exclusion list to exclude Meetings and FAQ_ - done
- [ ] Only first-level item goes to table of contents - this is what I think we need to fix, it's 6 pages now. @onthebreeze - would you agree?

**Comment by onthebreeze** [comment]
all good thanks - and yes, just top level items in ToC is probably good.
