### ISSUE TITLE
DPP Evidence property - use VCDM structure or not?

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/spec-untp#42]
with reference to the discussion at Pull request #41 , this ticket is to trigger a discussion about whether / how to use the VCDM evidence property https://www.w3.org/TR/vc-data-model-2.0/#evidence or whether the evidence links should be within the DPP credential subject.

- Pro's of VCDM.  It's part of the W3C VC data model recommendation.  
- challenges of using VCDM.  There could be dozens of evidence references, each specific to the context in which it is referenced (eg an emissions credential referenced from an emissions claim).  If all evidence is grouped at the header level of a VC, then it could be trickier to figure out which evidence supports which claim.

For discussion...

**Comment by monkeypants** [comment]
In the VCDM, evidence is a property of the VC that supports the integrity of the claims in the VC. It's not clear to me if it is only a property of the VC, or if it can be a property of a specific the claim?

In the DPP data model, evidence supports a specific individual (typed) claim e.g. a Conformity claim, Facility.location, Party.identity, ProductInformation.ownership claims. If the VCDM evidence property can be used in that way, it seems like maybe it could be used.

**Comment by seewodg** [comment]
@monkeypants It appears that the evidence object in a VC instance, may optionally include an id property that if present SHOULD be a URL (the standard specifies URL not URI) that points to where more information about this instance of evidence can be found (according to the standard).

Anything else can declare its own type of "Evidence" for claims, or reuse/extend the standardised VC version of evidence. Governing authorities may even place constraints on Sustainability Claim evidence as a requirement for their particular market.

As to whether or not Evidence as modelled for VC is suitable for other claim types such as Sustainability Claims could be tested. Would there for example be a different rule for Evidence for Sustainability Claim instances that states something like "A URI that links to the evidence instances MUST be resolvable to blah resolver party"?

**Comment by PatStLouis** [comment]
@onthebreeze there's the evidence property in the `ConformityAttestation` object of the `ConformityCredential`.

How about we move the evidence to the base layer of the vc and use the evidence field of the VCDM 2.0, we just define an evidence type `ConformityAttestationEvidence` and keep the current evidence structure? Seems like a simple and elegant solution.

From the VCDM 2.0 spec:

> The precise content of each evidence scheme is determined by the specific evidence type definition.
We just point that type to:

https://uncefact.github.io/spec-untp/docs/specification/ConformityCredential#evidence
