### ISSUE TITLE
Credential subject

### ISSUE THREAD

**Issue by philarcher** [uncefact/spec-untp#47]
In the [current draft of the VC section](https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport/#verifiablecredential) of the DPP spec, the table shows that the credential subject should be the Product passport. Really??? In my world view it should be the product. The subject of a VC is not the VC itself. What have I misunderstood?

**Comment by PatStLouis** [comment]
The Product is a component of the Product Passport. The Product Passport is the cumulation of the Product + other components associated. The VC is a Digital Product Passport Credential but the subject is the Product Passport, which will also be represented in other mediums such as PDF. VC's are often a digitally secured representation of physical documents.

Looking at the [Bachelor Degree credential example](https://www.w3.org/TR/vc-data-model-2.0/#example-usage-of-the-credentialsubject-property) from the VCDM specification, The VC type is `ExampleDegreeCredential` but the credentialSubjet type is `ExampleBachelorDegree`. In the same way, the DPP VC would have a type of `DigitalProductPassportCredential` and the credential subject would be the `DigitalProductPassport` itself. The DPP would then contain other subjects such as the Product, the Batch, etc...

**Comment by philarcher** [comment]
I still struggle with this a little but I'm not going to argue. Thanks
