### ISSUE TITLE
Include the actual YAML for the DPP schema on the spec page

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#5]
Linking to https://jargon.sh/user/unece/ConformityCredential/v/working/artefacts/readme/render is difficult to interpret

**Comment by nissimsan** [comment]
Tagging @colugo ^

**Comment by colugo** [comment]
Although now having read the issue title, I understand a little more ;)

I can manually add the YAML (although JSON would seem more natural, no?) now, and can look into having it automatically updated in the future.

**Comment by colugo** [comment]
I've manually added the schema as YAML. It will not automatically update, and so runs the risk of becoming stale. Still, take a look and see if it addresses your concerns, and I can look into having Jargon auto-populate the up-to-date schema as part of the standard readme functionality.

https://jargon.sh/user/unece/ConformityCredential/v/working/artefacts/readme/render#conformityattestation-schema

**Comment by nissimsan** [comment]
Great, @colugo, thanks a bunch! That's precisely what I was aiming for. This makes it much more tangible. 

Ultimately we probably want to include that YAML on https://uncefact.github.io/spec-untp/docs/specification/DigitalProductPassport at some point. Maybe. But that's for later - let's focus on the data modelling for now. 

Cheers!
