### ISSUE TITLE
Trim the spec sections

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#62]
hi team - something I want to discuss today.  i think we have too many headings under https://uncefact.github.io/spec-untp/docs/specification/.  It's not so much that I think some need to be merged but rather I think some are genuinely testable normative specifications and some are really more like informative best practices.  So I'm gonna suggest that the first 7 headings (architecture down to verifiable credentials) can be normative specs and the last 7 (data carriers to ESG rules) can be informative best practices.  Maybe over time some really solid practices will emerge that trigger us to lift some some of the practices to become specifications.  But lets not force that now.  Also makes the implementation scope simpler and more understandable. 

I support trimming the headlines. Some, I think, can be bundled into, say, a “Design Patterns” section (with mass balance, anti-counterfeiting, confidentiality…)

**Comment by onthebreeze** [comment]
I'd like to propose a minor re-structure of the current site architecture from what you see now at https://uncefact.github.io/spec-untp/docs/about/ - which looks like this:

# From This 
### About the UNTP
 - Audience, Benefits & Goals
 - Requirements  
 - Governance  
 - Pledge  
 - FAQ  
### Specification  
 - Architecture  
 - Digitial Product Passport  
 - Conformity Credential  
 - Traceability Events  
 - Identifiers  
 - Vocabularies  
 - Verifiable Credentials  
 - Data Carriers  
 - Trust Anchors  
 - Trust Graphs  
 - Confidentiality  
 - Anti-Counterfeiting  
 - Mass Balance  
 - ESG Rules
### Business Case  
 - For Regulators  
 - For Industry  
 - For Industry Associations  
 - For Certifiers  
 - For Software Vendors  
### Tools and support  
 - Test Cases  
 - Test Service  
 - Tools  
 - Support  
### Extensions Register  
 - Extensions Methodology  
 - Extensions Register  
### Implementations Register  
 - Conformity  
 - Register

# To this

Changes are in **bold** text 

### About the UNTP
 - Audience, Benefits & Goals
 - Requirements  
 - Governance  
 - **Meetings**
 - Pledge  
 - FAQ  
### Specification  
 - Architecture  
 - Digital Product Passport  
 - Conformity Credential  
 - Traceability Events  
 - Identifiers  
 - Vocabularies  
 - Verifiable Credentials  
 - Data Carriers  
 ### Design Patterns
 - Trust Anchors  
 - Trust Graphs  
 - Confidentiality  
 - Anti-Counterfeiting  
 - Mass Balance  
 - ESG Rules
### Implementation Guidance 
 - **For Value Chain Actors**
 - **For Identifier Issuers**
 - **For Conformity Assessment Bodies**
 - **For Standards bodies**
 - **For Regulators**
 - Test Tools
 - Community Support
### Business Case  
 - **For Producers & Manufacturers**
 - **For Brands & Retailers** 
 - For Regulators  
 - For Industry Associations  
 - For Certifiers 
 - For Software Vendors  
### Extensions Register  
 - Extensions Methodology  
 - Extensions Register  
### Implementations Register  
 - Conformity Levels
 - Register

**Comment by onthebreeze** [comment]
I'll prepare a PR with this re-structure.  Please add your objections or suggestions to this ticket.

**Comment by zachzeus** [comment]
Do we want to add 'Implementation Tools' to the implementation guidance section?

**Comment by onthebreeze** [comment]
closed with pr https://github.com/uncefact/spec-untp/pull/85
