### ISSUE TITLE
Create a contributors instructions page

### ISSUE THREAD

**Issue by zachzeus** [uncefact/spec-untp#64]
A section of how to add contributions.  This probably would be something that lives in a 'governance' section.

**Comment by VladimirAlexiev** [comment]
hi @zachzeus and @onthebreeze and @nissimsan !
This is a good start, but only regarding the text of the spec.

How do we make changes to models?
- How can one join https://jargon.sh/user/unece/DigitalProductPassport as collaborator?
- Should we first post an issue or can directly edit the model? I strongly recommend first making an issue to allow a discussiont o happen
- Should we pust issues on Github or Jargon? I strongly recommend Github: Jargon looks very good (emulates Github) but is a lot less functional:
  - cannot open model and list of issues in separate browser tabs (!?!)
  - cannot link to specific issue
  - does not show diffs (or maybe I don't see where)

**Comment by nissimsan** [comment]
> Should we pust issues on Github or Jargon? I strongly recommend Github

+1
