### ISSUE TITLE
Product Granularity Level

### ISSUE THREAD

**Issue by GerhardHNL** [uncefact/spec-untp#72]
Would adding **'Product Granularity Level'** (model, batch, serialized item) to the entity 'Product Passport' make it more prominent what the product is about, as for each product, different combinations could exists: Model+Batch, Model+Serialized Item. I am aware of the application identifiers that can be used in a barcode, adding more information into the identifier. But a product ID is not a barcode, it can be represented as such.

**Comment by onthebreeze** [comment]
Yes maybe it would.  Lets discuss at the next meeting. 

Any thoughts from our project team?

**Comment by onthebreeze** [comment]
added `granularityLevel` property to the DPP.  Will appear in the next release.
