### ISSUE TITLE
MassFraction

### ISSUE THREAD

**Issue by GerhardHNL** [uncefact/spec-untp#74]
A numeric value representing the mass fraction of the product represented by this material. The sum of all mass fraction values for a given passport should be 100.

Remark: Mathematically, mass fraction is calculated as the mass of the component of interest divided by the total mass of the mixture or material, expressed as a fraction or percentage. --> Therefore, the sum of all mass fraction values for a given passport should be 1. 

Would adding the weight of a component material be worthwhile in this context? E.g. 
Virgin Cotton, Material Weight 1 KGM, Mass Fraction 0,5.  
Organic Cotton Material Weight 1 KGM , Mass Fraction 0,5.

**Comment by onthebreeze** [comment]
yes, fair point.  Should sum to 1 not to 100.

updated https://test.uncefact.org/vocabulary/untp/core/0/massFraction

**Comment by onthebreeze** [comment]
I think this one can be closed.  Point accepted and updated in the spec.
