### ISSUE TITLE
why use VC 1.1 instead of 2.0?

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-untp#81]
Why do you use this context?
```js
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
```
In https://www.w3.org/TR/vc-data-model-2.0/#example-usage-of-issuer-property a newer version is used:
```js
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
```

Please also review the other imported contexts for being up to date:
```js
    "https://w3id.org/vc-revocation-list-2020/v1",
    "https://w3id.org/security/suites/jws-2020/v1",
    "https://w3id.org/security/suites/jws-2020/v1",
```
And remove the duplication of `jws-2020/v1`

**Comment by zachzeus** [comment]
The upgrade of our reference implementation from v1 to v2 is in flight we will shortly be updating demos and references to point at v2

**Comment by VladimirAlexiev** [comment]
Thanks @zachzeus ! Do you expect any issues, or it's just a matter of upgrading the reference URLs?
In other words, are VC 2.0 backward compatible in VC 1.1.

**Comment by onthebreeze** [comment]
We probably should not demand conformance with latest version until it is ubiquitously adopted

**Comment by PatStLouis** [comment]
I think supporting backwards compatibility for verifying is important but issuance should use the 2.0 version moving forward.

**Comment by VladimirAlexiev** [comment]
@onthebreeze can you comment what you fixed because I raised 3 separate subissues in the description
