### ISSUE TITLE
Setup google tag plugin for analitics

### ISSUE THREAD

**Issue by kshychko** [uncefact/spec-untp#89]
Please configure [google tag plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) for this repo to collect the analytics.
```
trackingID - G-9NBG7HW734
```

**Comment by webilhan** [comment]
@kshychko It looks like we need to install plugin for google analytics.
I've added config for it.

**Comment by kshychko** [comment]
@onthebreeze, we've got the google tag plugin set up for the website, here is the exported report of users visited by countries for the past month (efficiently - for the past day since the plugin was added):
[report.pdf](https://github.com/uncefact/spec-untp/files/15497185/report.pdf)

**Comment by onthebreeze** [comment]
Done - here's a report for last month
[UNTP_GA_Report_May2024.pdf](https://github.com/user-attachments/files/15797577/UNTP_GA_Report_May2024.pdf)
