### ISSUE TITLE
Align data models to the VC Data Model

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#91]
This issue stems from https://github.com/uncefact/spec-untp/pull/90

Several of our examples are based on an approach of essentially recreating the VC Data Model (which defines `issuer`, `validFrom`, etc..), with the intent to wrap that all into the `credentialSubject` of a VC. That will produce a quite inelegant data graph with a lot of duplication and potential for inconsistencies (`issuer` vs `issuedBy`, `validFrom` vs `validFrom`...).

Rather, we want to leverage the VCDM. For example `issuer`, should be added within a complex object instead of repeating it within the `credentialSubject`. For example:

  ...
  "issuer": {
    "@type": [
      "Organization"
    ],
    "@id": "did:web:nis.example.com",
    "taxIdentificationNumnber": "DK-12345678",
    "name": "Nis Global Unltd.",
    "street": "Ocean Lane 100",
    "locality": "Paradise Island",
    "country": "DK"
  },
  "credentialSubject": {
    "type": [
      "ConformityStuff"
    ],
    "aClaim": "conforming",
    "anotherClaim": "legit",
    ...

**Comment by JohnOnGH** [comment]
I think it would be useful to have some form of highlighting of where the spec we define follows the the standard W3C VC DM, and where we are adding something we need for UNTP.

**Comment by PatStLouis** [comment]
Let's bundle addressing issue #42 with this.

**Comment by PatStLouis** [comment]
@nissimsan along the same line of thinking of migrating the `issuedBy` field to the issuer value of the vc, could we make the `issuedTo` the `credentialSubject`? and add a property called `hasAttestation`?

**Comment by PatStLouis** [comment]
I wanted to add leveraging the `credentialSchema` feature of the core data model to carry schema information.

**Comment by onthebreeze** [comment]
Yes will add that. Leave this open till done
