### ISSUE TITLE
Support for Co-signing / Counter-signing / Multi-signature

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-untp#99]
Conformity certificates often carry more than one signature. I would like to see this group suggest a common data model to support this. 

Off the top of my head, I could imagine something like a `CountersignCredential` which either includes the entire already-signed credential, and/or references.

**Comment by Fak3** [comment]
Proof chain and proof set are supported in vcdi: https://www.w3.org/TR/vc-data-integrity/#proof-chains

**Comment by PatStLouis** [comment]
I also recommend the parallel signatures feature of the data integrity securing mechanism which addresses just that.

**Comment by onthebreeze** [comment]
So - do we have consensus that

1. Multiple signatures is something UNTP wants to support?
2. If we do support it then https://www.w3.org/TR/vc-data-integrity/#proof-chains is the method?
